### PR TITLE
Lock NodeJS and Alpine versions

### LINKED ISSUE #14: Actions fails
With the following error:

```
  npm ERR! The `npm ci` command can only install with an existing package-lock.json or
  npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
  npm ERR! later to generate a package-lock.json file, then try again.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2020-10-25T19_44_30_633Z-debug.log
```

Looking at the `Dockerfile` I guess it's because there is no nodejs version constraint?

### PR DESCRIPTION
**Pull request by WyriHaximus**
Resolves: #14

### CODE REVIEW

**Comment by CleanCut** [comment]
@JasonEtco Gentle nudge. This action appears to be completely broken at the moment. If this would fix it, it would be great to merge.

**Review by JasonEtco — APPROVED** [review]
Thanks for the fix @WyriHaximus!

**Comment by WyriHaximus** [comment]
No problem @JasonEtco! Are you planning to create a new release soon as if you're using it as `JasonEtco/is-sponsor-label-action@v1` it still fails?

**Comment by tomkerkhove** [comment]
Same here

**Pull request merged**
